section "Bank 01",romx,bank[$01]
incbin "bounced.gbc",$4000,$4000

section "Bank 02",romx,bank[$02]
incbin "bounced.gbc",$8000,$4000

section "Bank 03",romx,bank[$03]
incbin "bounced.gbc",$c000,$4000

section "Bank 04",romx,bank[$04]
incbin "bounced.gbc",$10000,$4000

section "Bank 05",romx,bank[$05]
incbin "bounced.gbc",$14000,$4000

section "Bank 06",romx,bank[$06]
incbin "bounced.gbc",$18000,$4000

section "Bank 07",romx,bank[$07]
incbin "bounced.gbc",$1c000,$4000

section "Bank 08",romx,bank[$08]
incbin "bounced.gbc",$20000,$4000

section "Bank 09",romx,bank[$09]
incbin "bounced.gbc",$24000,$4000

section "Bank 0a",romx,bank[$0a]
incbin "bounced.gbc",$28000,$4000

section "Bank 0b",romx,bank[$0b]
incbin "bounced.gbc",$2c000,$4000

section "Bank 0c",romx,bank[$0c]
incbin "bounced.gbc",$30000,$4000

section "Bank 0d",romx,bank[$0d]
incbin "bounced.gbc",$34000,$4000

section "Bank 0e",romx,bank[$0e]
incbin "bounced.gbc",$38000,$4000

section "Bank 0f",romx,bank[$0f]
incbin "bounced.gbc",$3c000,$4000

section "Bank 10",romx,bank[$10]
incbin "bounced.gbc",$40000,$4000

section "Bank 11",romx,bank[$11]
incbin "bounced.gbc",$44000,$4000

section "Bank 12",romx,bank[$12]
incbin "bounced.gbc",$48000,$4000

section "Bank 13",romx,bank[$13]
incbin "bounced.gbc",$4c000,$4000

section "Bank 14",romx,bank[$14]
incbin "bounced.gbc",$50000,$4000

section "Bank 15",romx,bank[$15]
incbin "bounced.gbc",$54000,$4000

section "Bank 16",romx,bank[$16]
incbin "bounced.gbc",$58000,$4000

section "Bank 17",romx,bank[$17]
incbin "bounced.gbc",$5c000,$4000

section "Bank 18",romx,bank[$18]
incbin "bounced.gbc",$60000,$4000

section "Bank 19",romx,bank[$19]
incbin "bounced.gbc",$64000,$4000

section "Bank 1a",romx,bank[$1a]
incbin "bounced.gbc",$68000,$4000

section "Bank 1b",romx,bank[$1b]
incbin "bounced.gbc",$6c000,$4000

section "Bank 1c",romx,bank[$1c]
incbin "bounced.gbc",$70000,$4000

section "Bank 1d",romx,bank[$1d]
incbin "bounced.gbc",$74000,$4000

section "Bank 1e",romx,bank[$1e]
incbin "bounced.gbc",$78000,$4000

section "Bank 1f",romx,bank[$1f]
incbin "bounced.gbc",$7c000,$4000
